version: "3.8"

services:
  nginx:
    container_name: nginx_wp
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_net
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_htpasswd:/etc/nginx/htpasswd
      - nginx_cert:/etc/nginx/cert
      - wordpress:/var/www/html
    depends_on:
      - wordpress


  wordpress:
    container_name: wordpress
    image: kyrtsun/custom_wp
    networks:
      - nginx_net
    volumes:
      - wordpress:/var/www/html
      - nginx_cert:/var/www/html/all_config/nginx/cert
      - nginx_conf:/var/www/html/all_config/nginx/nginx.conf
      - nginx_htpasswd:/var/www/html/all_config/nginx/htpasswd
    depends_on:
      - database


  database:
    container_name: database
    image: mysql:8.0
    expose:
      - "3306"
    networks:
      - nginx_net
    environment:
      - MYSQL_DATABASE=DB_NAME
      - MYSQL_USER=USER
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - database:/var/lib/mysql



networks:
  nginx_net:

volumes:
  database:
  wordpress:
  nginx_cert:
  nginx_conf:
  nginx_htpasswd:
