version: "3.8"

services:
  wordpress:
    container_name: wordpress
    env_file:
      - ./.env
    image: kyrtsun/custom_wp:${TAG}
    restart: unless-stopped
    networks:
      - nginx_wp_net
      - database
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - database


  database:
    container_name: database
    image: mysql:8.0
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - database
    environment:
      - MYSQL_DATABASE=DB_NAME
      - MYSQL_USER=USER
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - database:/var/lib/mysql



networks:
  database:
  nginx_wp_net:
    external: true

volumes:
  database:
  wordpress:
    external: true
