version: "3.8"

services:
  nginx:
    container_name: nginx_wp
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_net
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/cert:/etc/nginx/cert
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress


  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx_net
    volumes:
      - ./config.wp/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database


  database:
    container_name: database
    image: mysql:8.0
    expose:
      - "3306"
    networks:
      - nginx_net
    environment:
      - MYSQL_DATABASE=DB_NAME
      - MYSQL_USER=USER
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - database:/var/lib/mysql



networks:
  nginx_net:

volumes:
  database:

