name: Deploy on EC2

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      run: |
        sudo chmod +x wordpress_download.sh
        sudo ./wordpress_download.sh
        docker build -t kyrtsun/custom_wp .
        docker push kyrtsun/custom_wp

    - name: login EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}  
        username: ${{ secrets.EC2_USERNAME }}  
        key: ${{ secrets.EC2_KEY }} 
        port: ${{ secrets.EC2_PORT }}

        script: | 
          sudo docker stop database nginx_wp wordpress
          sudo docker rm database nginx_wp wordpress
          sudo docker rmi kyrtsun/custom_wp mysql:8.0 nginx:1.25
          sudo rm -r wordpress
          sudo mkdir wordpress && cd wordpress
          touch deploy.txt
          sudo svn export https://github.com/Kirtsun/wordpress/trunk/all_config/docker-compose.yml
          sudo docker-compose up -d
          echo "It works! date $(TZ="Europe/Kiev" date "+%A %d-%b-%Y %H:%M:%S %Z")" >> deploy.txt
