name: Deploy on EC2

on:
  workflow_dispatch:

jobs:

  create_image:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v3
      
    - name: log docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Make docker image
      run: |
        sudo chmod +x wordpress_download.sh
        sudo ./wordpress_download.sh
        docker build -t kyrtsun/custom_wp .
        docker push kyrtsun/custom_wp

  add_file:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ./all_config/nginx_wp/*
          target: /home/ubuntu/nginx/nginx_wp

      - name: copy wp docker file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ./all_config/docker-compose.yml
          target: /home/ubuntu/wordpress

  deploy:
    needs: create_image
    runs-on: ubuntu-latest
    steps:
      - name: login EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: | 
            sudo docker stop database wordpress nginx
            sudo docker rm database wordpress nginx
            sudo docker rmi kyrtsun/custom_wp mysql:8.0 nginx:1.25
            sudo docker volume rm wordpress
            sudo docker volume create wordpress
            cd wordpress
            sudo touch deploy_wordpress.txt
            sudo docker-compose up -d
            wait
            echo "It works! $(TZ="Europe/Kiev" date "+%A %d-%b-%Y %H:%M:%S %Z")" | sudo tee -a deploy_wordpress.txt

