name: Deploy on EC2

on:
  workflow_dispatch:

jobs:

  create_image:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v3
      
    - name: log docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Make docker image
      run: |
        sudo chmod +x wordpress_download.sh
        sudo ./wordpress_download.sh
        docker build -t kyrtsun/custom_wp .
        docker push kyrtsun/custom_wp


  deploy:
    needs: create_image
    runs-on: ubuntu-latest
    steps:
      - name: login EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: | 
            sudo docker stop database nginx_wp wordpress
            sudo docker rm database nginx_wp wordpress
            sudo docker rmi kyrtsun/custom_wp mysql:8.0 nginx:1.25
            sudo docker volume rm wordpress_nginx_conf wordpress_nginx_cert wordpress_nginx_htpasswd
            sudo rm -r wordpress
            sudo touch deploy_wordpress.txt
            sudo mkdir wordpress && cd wordpress
            sudo svn export https://github.com/Kirtsun/wordpress/trunk/all_config/docker-compose.yml
            sudo docker-compose up -d
            wait
            cd ..
            echo "It works! $(TZ="Europe/Kiev" date "+%A %d-%b-%Y %H:%M:%S %Z")" | sudo tee -a deploy_wordpress.txt

