name: TEST

on:
  workflow_dispatch:

jobs:

  create_image:
    runs-on: ubuntu-latest

    steps: 
      - name: echo
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > txt.txt
          base64 --decode txt.txt > ps.json
          cat ps.json
    
  






    
