name: TEST

on:
  workflow_dispatch:

jobs:

  create_image:
    runs-on: ubuntu-latest

    steps: 
          
      - name: gcp key to json
        run: echo ${{ secrets.GCP_SA_KEY_64 }} > gcp_sa_key.txt && base64 --decode gcp_sa_key.txt > gcp_sa_key.json

      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "$(cat gcp_sa_key.json)"
      # - id: get-credentials
      #   uses: google-github-actions/get-gke-credentials@v2
      #   with:
      #     cluster_name: aifa-spot-agent
      #     location: us-central1
  
      # - name: create secret for gcr
      #   run: |
          
      #     kubectl delete secret gcr-json-key2 --ignore-not-found && \
      #     kubectl create secret docker-registry gcr-json-key2 \
      #       --docker-server=gcr.io \
      #       --docker-username=_json_key \
      #       --docker-password="$(cat gcp_sa_key.json)" \
      #       --docker-email=oleh.kyrtsun@litslink.com
   




    
