name: Deploy on EC2

on:
  workflow_dispatch:

jobs:

  create_image:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v3
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
  
      - name: Configure docker
        run: gcloud auth configure-docker
  
      - name: Make Docker Image
        run: |
          sudo chmod +x wordpress_download.sh
          sudo ./wordpress_download.sh
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/test:${{ toJSON(github.run_number) }} -f Dockerfile .
  
      - name: Push Docker Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/aifa:${{ toJSON(github.run_number) }}
